export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_AGE_MIN = 'UPDATE_AGE_MIN';
export const UPDATE_AGE_MAX = 'UPDATE_AGE_MAX';
export const UPDATE_TYPE_PREFERENCE = 'UPDATE_TYPE_PREFERENCE';
export const FETCH_PETS = 'FETCH_PETS';